table_cols = {
	'Activity': ['SiteID', 'iCurrencyDecimals', 'iTaxDecimals', 
		'dcTax1Rate_Rent', 'dcTax2Rate_Rent', 'WaitingID', 'TenantID', 
		'LedgerID', 'UnitID', 'sUnitName', 'sSize', 'dcWidth', 'dcLength', 
		'dcArea', 'bMobile', 'bClimate', 'bAlarm', 'bPower', 'bInside', 
		'iFloor', 'dcPushRate', 'dcStdRate', 'UnitTypeID', 'sTypeName', 
		'bChargeTax1', 'bChargeTax2', 'iDefLeaseNum', 'ConcessionID', 
		'sPlanName', 'iPromoGlobalNum', 'sPromoDescription', 
		'QTCancellationTypeID', 'dPlaced', 'dFollowUp', 'dFollowUpLast', 
		'dCancelled', 'dExpires', 'dLease', 'iDaysWorked', 'dcPaidReserveFee',
		'iCallType', 'sCallType', 'sCancellationReason', 'sFName', 'sMI',
		'sLName', 'sTenantName', 'sCompany', 'bCommercial', 'dcInsurPremium',
		'iLeaseNum', 'iAutoBillType', 'sAutoBillType', 'bInvoice', 
		'dcSchedRent', 'dSchedRentStrt', 'sEmployeeName', 'sEmployeeFollowUp',
		'sEmployeeConvertedToRes', 'sEmployeeConvertedToMoveIn', 
		'sEmployeeNameInitials', 'sEmployeeFollowUpInitials', 
		'sEmployeeConvertedToResInitials', 'sEmployeeConvertedToMoveInInitials',
		'iInquiryType', 'sInquiryType', 'MarketingID', 'sMarketingDesc', 
		'QTRentalTypeID', 'sRentalType', 'dConverted_ToRsv', 'dNeeded', 
		'sCancellationReason1', 'sEmail', 'sComment', 'sPhone', 
		'iGlobalWaitingNum', 'sSource', 'sPostalCode', 'sCallerID', 
		'sTrackingNum', 'iInquiryConvertedToLease', 
		'iReservationConvertedToLease', 'dcRate_Quoted', 'sCorpCode', 
		'sLocationCode'],
	'Summary': ['SiteID', 'rowOrder', 'iOrder', 'sSource', 'iPlacedInq', 
		'iPlacedRsv', 'iPlaced', 'iInqConvertedToRsv', 'iFollowupsSched', 
		'iFollowupsMade', 'iCancelled', 'iExpired', 'iConvertedToLease', 
		'iMoveInNoWaiting', 'dcCancelled_Percent', 'dcConverted_Percent', 
		'sCorpCode', 'sLocationCode'],
	'Cancelled': ['SiteID', 'rowOrder', 'iOrder', 'sSource', 'iCount', 
		'sCorpCode', 'sLocationCode'],
	'Marketing': ['SiteID', 'rowOrder', 'sMarketingDesc', 'Column1', 
		'iConverted', 'iTotal', 'sCorpCode', 'sLocationCode'],
	'InquirySource': ['SiteID', 'rowOrder', 'sInquiryType', 'iTotal', 
		'iConverted', 'sCorpCode', 'sLocationCode'],
	'Employees': ['SiteID', 'rowOrder', 'iOrder', 'sEmployeeNameInitials',
		'sEmployeeName', 'iPlacedInq', 'iPlacedRsv', 'iPlaced', 
		'iInqConvertedToRsv', 'iFollowupsSched', 'iFollowUpLast', 'iCancelled', 
		'iExpired', 'iWaitingMoveIn', 'iConvertedToLease', 'iMoveInNoWaiting', 
		'dcCancelled_Percent', 'dcConverted_Percent', 'sCorpCode', 
		'sLocationCode'],
	'Sites': ['SiteID', 'rowOrder', 'sSiteName', 'sSiteAddress', 'sSiteAddr1', 
		'sSiteAddr2', 'sSiteCity', 'sSiteRegion', 'sSitePostalCode', 
		'sSiteCountry', 'sSiteCode', 'sEmailAddress', 'sSitePhone', 'sSiteFax',
		'CurrencyDecimalPlaces', 'iTaxDecimalPlaces', 'bShowAreasInsteadOfSize',
		'bAccrual', 'sAcctSoftwareCode', 'bAcctProrateAR', 
		'bPrepaidRentLiabilityAcct', 'sSoftwareName', 'bUseInclusiveTaxation', 
		'LocationName', 'AccountName', 'StartDate', 'sCorpCode', 
		'sLocationCode']
}